image: maven:3.6.3

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvnclean compile install -DskipTests -e


test:
  stage: test
  script:
    - mvn test
